using Workcast.Core.Enums;
using Workcast.Core.Models;

namespace Workcast.Core.Entities;

/// <summary>
/// Represents a registered job board URL. The root aggregate of the scraping domain.
/// </summary>
public class JobBoard
{
    // NOTE: Parameterless constructor required by EF Core. Public properties with
    // private setters are used so EF can materialise instances from the database.
    private JobBoard() { }

    /// <summary>
    /// Creates a new <see cref="JobBoard"/> in the <see cref="BoardStatus.Pending"/> state.
    /// Board analysis must complete before the board becomes active.
    /// </summary>
    /// <param name="url">The seed URL provided by the user.</param>
    /// <param name="name">Optional display name. Auto-populated from the page title after analysis.</param>
    /// <param name="scheduleCron">Optional cron expression. Defaults to hourly if not provided.</param>
    public static JobBoard Create(string url, string? name = null, string? scheduleCron = null)
    {
        return new JobBoard
        {
            Url = url,
            Name = name,
            Status = BoardStatus.Pending,
            // NOTE: TECHSPEC section 7.4 specifies "0 * * * *" (every hour on the hour) as
            // the default. Section 3.2 shows "0 0 * * *" (daily). Section 7.4 takes precedence
            // as it is the dedicated scheduling section.
            ScheduleCron = scheduleCron ?? "0 * * * *",
        };
    }

    /// <summary>UUID primary key, generated by the database.</summary>
    public Guid Id { get; private set; }

    /// <summary>Display name. Nullable — auto-populated from page title after board analysis.</summary>
    public string? Name { get; private set; }

    /// <summary>The seed URL registered by the user.</summary>
    public string Url { get; private set; } = string.Empty;

    /// <summary>
    /// AI-generated scraping configuration stored as JSONB.
    /// Null until board analysis completes successfully.
    /// </summary>
    public ScraperConfig? ScraperConfig { get; private set; }

    /// <summary>Cron expression defining the scraping schedule.</summary>
    public string ScheduleCron { get; private set; } = "0 * * * *";

    /// <summary>Current lifecycle status of the board.</summary>
    public BoardStatus Status { get; private set; }

    /// <summary>UTC timestamp of the last completed scrape run. Null until the first run.</summary>
    public DateTimeOffset? LastScrapedAt { get; private set; }

    /// <summary>UTC timestamp when the board was registered. Set by the EF Core interceptor.</summary>
    public DateTimeOffset CreatedAt { get; private set; }

    /// <summary>UTC timestamp of the last modification. Maintained by the EF Core interceptor.</summary>
    public DateTimeOffset UpdatedAt { get; private set; }

    /// <summary>Navigation property — all scrape runs for this board.</summary>
    public ICollection<ScrapeRun> ScrapeRuns { get; private set; } = new List<ScrapeRun>();

    /// <summary>Navigation property — all job ads scraped from this board.</summary>
    public ICollection<JobAd> JobAds { get; private set; } = new List<JobAd>();

    /// <summary>
    /// Marks the board as active after a successful board analysis.
    /// Sets the <see cref="ScraperConfig"/> and transitions status to <see cref="BoardStatus.Active"/>.
    /// </summary>
    public void Activate(ScraperConfig config)
    {
        ScraperConfig = config;
        Status = BoardStatus.Active;
    }

    /// <summary>
    /// Transitions the board to <see cref="BoardStatus.Error"/>.
    /// Called when board analysis or repeated scraping fails.
    /// </summary>
    public void SetError()
    {
        Status = BoardStatus.Error;
    }

    /// <summary>Pauses recurring scraping. Transitions status to <see cref="BoardStatus.Paused"/>.</summary>
    public void Pause()
    {
        Status = BoardStatus.Paused;
    }

    /// <summary>
    /// Resumes recurring scraping after a pause.
    /// Transitions status to <see cref="BoardStatus.Active"/>.
    /// </summary>
    public void Resume()
    {
        Status = BoardStatus.Active;
    }

    /// <summary>Updates the seed URL of this board.</summary>
    public void UpdateUrl(string url)
    {
        Url = url;
    }

    /// <summary>
    /// Updates the display name of this board.
    /// </summary>
    public void UpdateName(string? name)
    {
        Name = name;
    }

    /// <summary>
    /// Updates the cron schedule expression. The caller is responsible for
    /// re-registering the Hangfire recurring job after calling this method.
    /// </summary>
    public void UpdateSchedule(string scheduleCron)
    {
        ScheduleCron = scheduleCron;
    }

    /// <summary>Records the UTC time of the most recently completed scrape run.</summary>
    public void RecordScrapeCompleted()
    {
        LastScrapedAt = DateTimeOffset.UtcNow;
    }

    /// <summary>
    /// Replaces the scraper config after a re-analysis.
    /// Does not change the board status — the board remains in its current state.
    /// </summary>
    public void UpdateScraperConfig(ScraperConfig config)
    {
        ScraperConfig = config;
    }
}
