using Workcast.Core.Enums;

namespace Workcast.Core.Models;

/// <summary>
/// Structured scraping configuration stored as JSONB on <see cref="Workcast.Core.Entities.JobBoard"/>.
/// Generated by the AI board analysis step and stored verbatim per TECHSPEC section 3.5.
/// Job ad fields are extracted deterministically using <see cref="FieldSelectors"/> applied to each
/// <see cref="JobCardSelector"/> element — no per-ad AI call is made.
/// </summary>
public record ScraperConfig
{
    /// <summary>Pagination strategy for this board's listing pages.</summary>
    public required PaginationType PaginationType { get; init; }

    /// <summary>CSS selector that identifies each job card element on a listing page.</summary>
    public required string JobCardSelector { get; init; }

    /// <summary>Per-field CSS selectors applied relative to each job card element.</summary>
    public required FieldSelectorMap FieldSelectors { get; init; }

    /// <summary>CSS selector for the "next page" button, or null if not applicable.</summary>
    public string? NextPageSelector { get; init; }

    /// <summary>URL query parameter name used for pagination (e.g. "page"), or null.</summary>
    public string? UrlParamName { get; init; }

    /// <summary>True when the URL parameter represents an item offset rather than a page number.</summary>
    public bool UrlParamIsOffset { get; init; }

    /// <summary>Maximum number of pages to scrape as a safety cap. Null means unlimited.</summary>
    public int? MaxPages { get; init; }

    /// <summary>True when the board requires JavaScript execution to render job listings.</summary>
    public required bool RequiresJs { get; init; }

    /// <summary>Recommended delay in milliseconds between requests (politeness delay).</summary>
    public required int SuggestedDelayMs { get; init; }

    /// <summary>AI confidence in the generated config, from 0.0 to 1.0.</summary>
    public required float ConfidenceScore { get; init; }

    /// <summary>Free-text notes from the AI about unusual patterns on this board.</summary>
    public string? AnalyzerNotes { get; init; }

    /// <summary>UTC timestamp when this config was generated.</summary>
    public required DateTimeOffset GeneratedAt { get; init; }
}
