// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Workcast.Infrastructure.Persistence;

#nullable disable

namespace Workcast.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324064207_AddApplications")]
    partial class AddApplications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Workcast.Core.Entities.AdScoring", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("JobAdId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_ad_id");

                    b.Property<double>("OverallScore")
                        .HasColumnType("double precision")
                        .HasColumnName("overall_score");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("requirements");

                    b.Property<DateTimeOffset>("ScoredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("scored_at");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.HasIndex("JobAdId")
                        .IsUnique()
                        .HasDatabaseName("ix_ad_scorings_job_ad_id");

                    b.ToTable("ad_scorings", (string)null);
                });

            modelBuilder.Entity("Workcast.Core.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("BoardAnalyzerModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("board_analyzer_model");

                    b.Property<byte[]>("ResumeContent")
                        .HasColumnType("bytea")
                        .HasColumnName("resume_content");

                    b.Property<string>("ResumeContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resume_content_type");

                    b.Property<string>("ResumeFileName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("resume_file_name");

                    b.Property<DateTimeOffset?>("ResumeUploadedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("resume_uploaded_at");

                    b.Property<string>("ScoringModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scoring_model");

                    b.HasKey("Id");

                    b.ToTable("app_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoardAnalyzerModel = "claude-sonnet-4-5",
                            ScoringModel = "claude-haiku-4-5-20251001"
                        });
                });

            modelBuilder.Entity("Workcast.Core.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Company")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsTrashed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_trashed");

                    b.Property<Guid?>("JobAdId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_ad_id");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<double?>("OverallScore")
                        .HasColumnType("double precision")
                        .HasColumnName("overall_score");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("posted_at");

                    b.Property<string>("Recommendation")
                        .HasColumnType("text")
                        .HasColumnName("recommendation");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("requirements");

                    b.Property<string>("SalaryRaw")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("salary_raw");

                    b.Property<DateTimeOffset?>("ScoredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("scored_at");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_applications_created_at_desc");

                    b.HasIndex("IsTrashed")
                        .HasDatabaseName("ix_applications_is_trashed");

                    b.HasIndex("JobAdId")
                        .HasDatabaseName("ix_applications_job_ad_id");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("Workcast.Core.Entities.JobAd", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Company")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_pinned");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<bool>("IsScoringPending")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrashed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JobBoardId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_board_id");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("posted_at");

                    b.Property<string>("SalaryRaw")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("salary_raw");

                    b.Property<Guid?>("ScrapeRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("scrape_run_id");

                    b.Property<DateTimeOffset>("ScrapedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("scraped_at");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ScrapeRunId");

                    b.HasIndex("ScrapedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_job_ads_scraped_at_desc");

                    b.HasIndex("JobBoardId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_job_ads_job_board_id_external_id")
                        .HasFilter("external_id IS NOT NULL");

                    b.HasIndex("JobBoardId", "IsActive")
                        .HasDatabaseName("ix_job_ads_job_board_id_is_active");

                    b.HasIndex("JobBoardId", "Url")
                        .IsUnique()
                        .HasDatabaseName("ix_job_ads_job_board_id_url");

                    b.ToTable("job_ads", (string)null);
                });

            modelBuilder.Entity("Workcast.Core.Entities.JobBoard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastScrapedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_scraped_at");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("ScheduleCron")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("schedule_cron");

                    b.Property<string>("ScraperConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("scraper_config");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_job_boards_status");

                    b.ToTable("job_boards", (string)null);
                });

            modelBuilder.Entity("Workcast.Core.Entities.ScrapeRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AdsFound")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("ads_found");

                    b.Property<int>("AdsNew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("ads_new");

                    b.Property<string>("Errors")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("errors");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("finished_at");

                    b.Property<Guid>("JobBoardId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_board_id");

                    b.Property<int>("PagesScraped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("pages_scraped");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("triggered_by");

                    b.HasKey("Id");

                    b.HasIndex("JobBoardId", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_scrape_runs_job_board_id_started_at_desc");

                    b.ToTable("scrape_runs", (string)null);
                });

            modelBuilder.Entity("Workcast.Core.Entities.AdScoring", b =>
                {
                    b.HasOne("Workcast.Core.Entities.JobAd", "JobAd")
                        .WithMany()
                        .HasForeignKey("JobAdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobAd");
                });

            modelBuilder.Entity("Workcast.Core.Entities.JobAd", b =>
                {
                    b.HasOne("Workcast.Core.Entities.JobBoard", "JobBoard")
                        .WithMany("JobAds")
                        .HasForeignKey("JobBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workcast.Core.Entities.ScrapeRun", "ScrapeRun")
                        .WithMany("JobAds")
                        .HasForeignKey("ScrapeRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("JobBoard");

                    b.Navigation("ScrapeRun");
                });

            modelBuilder.Entity("Workcast.Core.Entities.ScrapeRun", b =>
                {
                    b.HasOne("Workcast.Core.Entities.JobBoard", "JobBoard")
                        .WithMany("ScrapeRuns")
                        .HasForeignKey("JobBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobBoard");
                });

            modelBuilder.Entity("Workcast.Core.Entities.JobBoard", b =>
                {
                    b.Navigation("JobAds");

                    b.Navigation("ScrapeRuns");
                });

            modelBuilder.Entity("Workcast.Core.Entities.ScrapeRun", b =>
                {
                    b.Navigation("JobAds");
                });
#pragma warning restore 612, 618
        }
    }
}
